import '@/src/shared/styles/global.scss';
import StoreProvider from "@/src/shared/configs/storeProvider";
import { Footer } from "@/src/widgets/footer";
import { Header } from "@/src/widgets/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CheckAuth } from '../features/checkAuth';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        
      <body className={inter.className}>
      <CheckAuth>
      <Header/>
        {children}
      <Footer/>
      </CheckAuth>
      </body>
      </StoreProvider>
    </html>
  );
}
