import localFont from 'next/font/local'
import '@/src/shared/styles/global.scss';
import StoreProvider from "@/src/shared/configs/storeProvider";
import { Footer } from "@/src/widgets/footer";
import { Header } from "@/src/widgets/header";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from "next";
import { CheckAuth } from '../features/checkAuth';
import { CartSaveAndLoad } from '../entities/cart';
import { ConfigProvider} from 'antd';
import theme from '../shared/themes/antTheme';



const pragmatica = localFont({
  src: '../../public/fonts/Pragmatica.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={pragmatica.className} id='__next'>
          <AntdRegistry>
          <ConfigProvider theme={theme}>
            <CheckAuth>
              <CartSaveAndLoad />
              <Header />
              {children}
              <Footer />
            </CheckAuth>
            </ConfigProvider>
          </AntdRegistry>
        </body>
      </StoreProvider>
    </html>
  );
}
